### ISSUE TITLE
A register without valid Serial number should be denied.

### ISSUE THREAD

**Issue by JM-Lemmi** [TINF21CS1/kilowatt_kojote#21]
A register without valid Serial number should be denied.

_Originally posted by @JM-Lemmi in https://github.com/TINF21CS1/kilowatt_kojote/issues/20#issuecomment-1826945656_

**Comment by Tayhm** [comment]
Inwiefern? Die serialnumber wird nicht überprüft, weil sie doch eh von der CA generiert wird
