### ISSUE TITLE
Meter sends location when registering

### ISSUE THREAD

**Issue by HOOK-Hawkins** [TINF21CS1/kilowatt_kojote#3]
To create an exact simulation, the meter must know its location. As it can not receive data, it must generate the location by itself and send them to the backend when registering. The backend and the swagger documentation must be changed accordingly

**Comment by Tayhm** [comment]
Wozu brauchst du denn einen Ort als Smartmeter? Reicht nicht der Typ?

**Comment by HOOK-Hawkins** [comment]
Ich mach über den gesamten Bereich ja eine Wetter-Simulation. Davon hängt der Verbrauch und die Produktion ab. Wäre ja doof, wenn ein Haushalt ganz viel Solarstrom produziert, während es daneben regnet und nacht ist

**Comment by Tayhm** [comment]
cool. ist aber dann halt nur unlogisch, dass du deine eigene position meldest

**Comment by HOOK-Hawkins** [comment]
Jaa, aber ich wüsste nicht wie das anders umsetzbar ist. Darum würde ich davon abweichen, dass das nicht ganz realistisch ist

**Comment by JM-Lemmi** [comment]
Der Smart Meter könnte durchaus seine Location kennen durch GPS (üblicherweise in LTE Modulen verbaut) o. Ä.

**Comment by Tayhm** [comment]
fixed in backend branch

**Comment by Tayhm** [comment]
max. 5 nachkommastellen @HOOK-Hawkins
